### ISSUE TITLE
Сортировка профилей

### ISSUE THREAD

**Issue by weerci** [weerci/LiteGeneLib#103]
Профили на основной форме и в диалоговом окне загрузки профилей должны быть отсортированы по имени

**Comment by Evgen-24** [comment]
1. число - число
2. число - буквы
3. буквы

**Comment by weerci** [comment]
Вроде так

**Comment by Evgen-24** [comment]
Не, не работает:

**Comment by Evgen-24** [comment]
![сортировка профилей-2](https://user-images.githubusercontent.com/45830240/62912647-41aa8280-bdb3-11e9-9f75-f25f9b9758b5.jpg)
![сортировка профилей-3](https://user-images.githubusercontent.com/45830240/62912649-41aa8280-bdb3-11e9-89a5-d2432e8d82f1.jpg)
![сортировка профилей-1](https://user-images.githubusercontent.com/45830240/62912650-42431900-bdb3-11e9-9ce4-0df9de69bed9.jpg)
