### ISSUE TITLE
Вид шаблона прямой идентификации (Excel)

### ISSUE THREAD

**Issue by Evgen-24** [weerci/LiteGeneLib#104]
Если не трудно, можно изменить в экселевском документе отображение: заменить "inverse" на  "1/P" и поместить на одну строчку ниже?
![Microsoft Excel - C8450CDD19B746B2BF3ABB20DCBB08D11   Режим совместимости  2019-08-11 23 43 05](https://user-images.githubusercontent.com/45830240/62836972-c43c2080-bc93-11e9-9ed0-c59f349cb3ba.jpg)

![Microsoft Excel - C8450CDD19B746B2BF3ABB20DCBB08D11   Режим совместимости  2019-08-11 23 43 58](https://user-images.githubusercontent.com/45830240/62836974-caca9800-bc93-11e9-8b9f-b0b4887c6040.jpg)

**Comment by weerci** [comment]
можно
