### ISSUE TITLE
Нет возможности выбора профиля в окне сравнения

### ISSUE THREAD

**Issue by Evgen-24** [weerci/LiteGeneLib#109]
Не критично.
При несовпадении профилей и выдачи сообщения о несовпадении, при нажатии "красной молнии", открывается окно сравнения, так вот в нем нельзя выбрать еще один профиль в свободном месте.
![невозможность выбора профиля в окне сравнения](https://user-images.githubusercontent.com/45830240/62915068-38beae80-bdbd-11e9-99ad-cf2a8dc601db.jpg)

**Comment by weerci** [comment]
Можно и прикрутить, если надо. Предполагалось, что будут отображаться не все, а только именно те, которые проблемные и кстати - если их больше предопределенных 4 столбцов - тогда они появляются в последнем выпадающемсписке

**Comment by Evgen-24** [comment]
Я не знал что так задумано. Не меняй ничего. Это просто наблюдение.
