### ISSUE TITLE
Не правильно считает LR!!! 

### ISSUE THREAD

**Issue by Evgen-24** [weerci/LiteGeneLib#110]
Ахтунг!
При делении прямой гипотезы на обратную выдает непонятное значение.

**Comment by weerci** [comment]
Женя, ну ты напиши где и как это повторить, это ж баг-трекер

**Comment by Evgen-24** [comment]
Ну так при делении прямой гипотезы на обратную, получается значение, не соответствующее данному делению. Повторить можно любым расчетом LR, и вручную разделить эти гипотезы.

**Comment by weerci** [comment]
Получается, что программа всегда неправильно считала. У меня ведь тесты всегда отрабатываются

**Comment by Evgen-24** [comment]
Нет. Версия 1.18.1.21 всё считает правильно. Причем версия, например 1.9.1.102, тоже считает неправильно, но по другому неправильно. результат в версиях 1.9.1.102 и 1.9.1.104 отличается.

**Comment by Evgen-24** [comment]
Проблема частично сохранилась: вместо значения обратной гипотезы, в шаблоне вставляется "1/прямой расчет прямой гипотезы"
![LR в шаблонах](https://user-images.githubusercontent.com/45830240/63653092-814d7300-c792-11e9-896b-411ab24643e8.jpg)
Причем само LR считается правильно. :-)

В расчетах с LR, расчет "1/Р" нигде не производится.
Вместо этого расчета (выделено красным) нужно добавить вывод итогового значения из колонки с обратной гипотезой.
![Microsoft Excel - Словарь Символов 2019-08-25 23 49 30](https://user-images.githubusercontent.com/45830240/63653133-10f32180-c793-11e9-8b5a-6e79baf7321c.jpg)
