### ISSUE TITLE
Импорт/Экспорт раздела "Контроль/Эксперт"

### ISSUE THREAD

**Issue by weerci** [weerci/LiteGeneLib#114]

**Comment by weerci** [comment]
На форме экспертов добавить кнопки импорт и экспорт, при нажатии на экспорт появляется форма со списком экспертов (список с галочками), пользователь выбирает нужных экспертов и нажимает ок - появляется форма сохранения файла. Файл с выбранными экспертами сохраняется.
Импорт происходит в обратном порядке - нажимается кнопка - форма выбора файла, выбор нужных экспертов

**Comment by Evgen-24** [comment]
Экспорт: появляется форма выбора генотипов из этого раздела (т.е. и **экспертов и контролей и профилей**), любой записи или записей из этого раздела. Название файла по умолчанию, например: "ind-27.08.2019" приставка-сегодняшняя дата. Приставки здесь и при экспорте БД (pub-27.08.2019) будут отличатся.
Импорт: аналогичное окно с выбором загружаемых данных. При совпадении имен: существующего в данном разделе и добавляемого, к добавляемому добавить числитель: 2... 3... и т.д.

**Comment by Evgen-24** [comment]
В окне контроль/эксперт правая область (где отображаются локусы и аллели) "уплыла" вверх.
