### ISSUE TITLE
Косметические исправления в окне расчета смесей

### ISSUE THREAD

**Issue by Evgen-24** [weerci/LiteGeneLib#115]
Корректное написание категорий лиц при расчетах смесей:
![Смесь 2019-08-27 20 39 41](https://user-images.githubusercontent.com/45830240/63782172-34de7080-c915-11e9-9977-b3d0b0cf98ce.jpg)
![Смесь 2019-08-27 20 39 46](https://user-images.githubusercontent.com/45830240/63782173-34de7080-c915-11e9-8670-e0e98165e077.jpg)
![Смесь 2019-08-27 20 39 52](https://user-images.githubusercontent.com/45830240/63782176-35770700-c915-11e9-88fa-5f112aac55b3.jpg)
![Смесь 2019-08-27 20 40 11](https://user-images.githubusercontent.com/45830240/63782177-35770700-c915-11e9-99f5-00e9d1710dc3.jpg)
![Смесь 2019-08-27 20 40 16](https://user-images.githubusercontent.com/45830240/63782179-360f9d80-c915-11e9-85b7-652efd84d8ad.jpg)
![Смесь 2019-08-27 20 40 21](https://user-images.githubusercontent.com/45830240/63782181-360f9d80-c915-11e9-8b94-7236b6055bcf.jpg)

**Comment by Evgen-24** [comment]
UPD:
Для полноты картины, если это не слишком проблематично, для более понятной визуализации таблицы, предлагаю названия столбцов назвать в соответствии с категориями профилей лица используемых при расчетах:

![названия колонок категорий](https://user-images.githubusercontent.com/45830240/64099819-6d0e0500-cd94-11e9-94da-9ec3fedc9e4c.jpg)

**Comment by weerci** [comment]
Закрыто версией 1.9.1.117
