### ISSUE TITLE
Баг с двойным кликом

### ISSUE THREAD

**Issue by Evgen-24** [weerci/LiteGeneLib#118]
При двойном клике по стрелке перемотки списка профилей - открывается профиль выделенный в этом списке.

![Глюк - Двойной клик по стрелке перемотки списка локусов ---](https://user-images.githubusercontent.com/45830240/64104544-99c71a00-cd9e-11e9-8630-581680f5329f.jpg)

**Comment by weerci** [comment]
Вообще со всеми списками ListView такой баг ( в экспертах, локусах и пр)
