### ISSUE TITLE
Косметические исправления в главном окне

### ISSUE THREAD

**Issue by Evgen-24** [weerci/LiteGeneLib#122]
В строке состояния текст вертикально не центрован (отступы сверху и снизу разные)
Предлагаю цветные прямоугольники, для единообразия, сделать кругами, размером как значок "молнии". Будет гармонично смотреться.

![отображение строки состояния](https://user-images.githubusercontent.com/45830240/64131866-b478ad80-cdf5-11e9-9967-f09fabbb49cf.jpg)

Ну и аналогично в окне "контроль/эксперт"

**Comment by Evgen-24** [comment]
В 117 версии без изменений.

**Comment by weerci** [comment]
Это в 118 будет :)
