### ISSUE TITLE
Михаил, вот нашел неточность 

### ISSUE THREAD

**Issue by weerci** [weerci/LiteGeneLib#41]
Михаил, вот нашел неточность -  формула одна в родстве пишется неправильно(?), смотри фото в приложении. Я в математике, так, "мимо походил", и в данном случае, даже по текущему написанию формулы, результат не меняется... но его заусило, что в методичке написание данной формулы другое. Он говорит что "двойка" должна быть за скобками:
сейчас выводится так: (p+p)*(2-p+p), а должно быть так: (p+p)*2-(p+p).

**Comment by Evgen-24** [comment]
Судя по всему, Михаил мне не правильно исправил формулу, правильная такая должна быть: (p + p) * (2-(p + p))
