### ISSUE TITLE
Важно! Ошибка с работой шестиаллельных профилей

### ISSUE THREAD

**Issue by Evgen-24** [weerci/LiteGeneLib#45]
Мы уже разбирали эту проблему и вроде бы решили, но видимо не до конца. Там проблема была в исходных файлах для экспорта - сохранялись только пять аллелей для локуса - в таком виде я и дал тебе самые первые файлы для экспериментов. НО!!! Когда мы это поняли, я сохранил несколько файлов для эксперимента с шестью аллелями - но они при загрузке все равно отображают не более пяти аллелей в локусе.
А) Если вручную внести шестиаллельный профиль, то он отображается корректно, считается корректно, в таблицу переносится корректно - то есть в этом варианте все нормально.
Б) Есть два      #####файла: (GE-329 Genotypes Table.txt и With OL and Spike and 6 alleleys.txt) которые созданы уже с сохранением шести аллелей в локусе:

- если загрузить «ALL» из файла «GE-329 Genotypes Table.txt», все равно загружаются только пять аллелей на локус, ПЛЮС еще вот такое «учетверение» локусов:
![image](https://user-images.githubusercontent.com/45830240/49925970-0e92b500-feed-11e8-9d5b-9fc07f8c82e8.png)

 почему так происходит, я не понимаю.
- при этом, если загрузить «All» из файла «With OL and Spike and 6 alleleys.txt», то также загружаются пять аллелей на локус, но «учетверения» локусов не происходит:
![image](https://user-images.githubusercontent.com/45830240/49925991-1c483a80-feed-11e8-969d-37929fac5f3f.png)
 

В обоих случаях, локусы, содержащие неизвестные аллели, не поддаются редактированию и появляется окно:
![image](https://user-images.githubusercontent.com/45830240/49926007-2a965680-feed-11e8-85e0-f753c8cc5913.png)

 
[With OL and Spike and 6 alleleys.txt](https://github.com/weerci/LiteGeneLib/files/2678786/With.OL.and.Spike.and.6.alleleys.txt)
[GE-329 Genotypes Table.txt](https://github.com/weerci/LiteGeneLib/files/2678787/GE-329.Genotypes.Table.txt)

**Comment by weerci** [comment]
Вышли файлы плиз для тестирования, по моему можно их сюда же к issue прикрутить
