### ISSUE TITLE
Единообразная сортировка локусов

### ISSUE THREAD

**Issue by Evgen-24** [weerci/LiteGeneLib#46]
Порядок любых отображений локусов должен ориентироваться на порядок локусов в настройках локусов:
I. обычные (расчетные)
II. не расчетные 
III. неизвестные (те которых нет в базе локусов).
![image](https://user-images.githubusercontent.com/45830240/49927873-8cf15600-fef1-11e8-83f6-a0b01fa73ba0.png)

**Comment by Evgen-24** [comment]
В последнем релизе сбилась сортировка.

**Comment by weerci** [comment]
Не увидел, вроде соответствует тому, что в форме локусов

**Comment by Evgen-24** [comment]
Не, я имел ввиду что сейчас отображаются:
I. обычные (расчетные)
II. неизвестные (те которых нет в базе локусов)
III. не расчетные.
А должны (как было в версиях 1.8):
I. обычные (расчетные)
II. не расчетные
III. неизвестные (те которых нет в базе локусов).

**Comment by weerci** [comment]
release

**Comment by Evgen-24** [comment]
В 114 не работает
![сортировка локусов](https://user-images.githubusercontent.com/45830240/63648588-2436ca80-c75c-11e9-9c1d-9c9a8e92520b.jpg)
Амелогенин должен быть выше DYS-ов. Амелогенин есть в базе, но он не расчетный, а дисов в базе нет.

I. обычные (расчетные)
II. не расчетные
III. неизвестные (те которых нет в базе локусов).

**Comment by weerci** [comment]
Не смог повторить может у тебя база не та?

**Comment by Evgen-24** [comment]
Ок.
