### ISSUE TITLE
Аллельный лэдер

### ISSUE THREAD

**Issue by weerci** [weerci/LiteGeneLib#50]
Помимо этого, проблемы с аллельным лэдером (в проектах часто обозначен как ALL) их часто в одном проекте два и более, а программой они, видимо, воспринимаются как один. Предполагаю, что поэтому при просмотре «генотипа» лэддера, там дублируются амелогенин и DYS-ы. Собственно, сам лэддер в проекте нас не интересует, просто опасаюсь, что это может аукнутся в каком либо объекте, так как DataCollection и GeneMapper  позволяют давать одинаковые названия объектам.

**Comment by Evgen-24** [comment]
Сделаю предупреждение в справке о том, что названия профилей должны быть уникальны в рамках одного проекта (экспортного файла).
