### ISSUE TITLE
Реактивное удаление

### ISSUE THREAD

**Issue by weerci** [weerci/LiteGeneLib#52]
При «залипшей» кнопке «DEL» удалил все профили по очереди (очень быстро), даже моргнуть не успел  8-). Сделай удаление как одно нажатие (полное) - одно удаление. Ну или как то еще, для исключения «реактивного удаления»?... То же происходит и с локусами и аллелями. (я в настройках отключил подтверждения на удаление).

**Comment by Evgen-24** [comment]
Ты говорил про таймеры, но я думал, что сам факт удаления, привязать не к нажатию кнопки, а к ее отпусканию (выделил локус - нажал "Del" - ничего не происходит - отпустил "Del" - произошло удаление - перемещение курсора на следующий локус). То есть не будет привязки ко времени и скорость удаления будет зависеть только от оператора - с какой скоростью будет нажиматься-отпускаться кнопка - с такой скоростью и будет удаление.

**Comment by weerci** [comment]
Сделал по KeyUp - странное ощущение при удалении :)
