### ISSUE TITLE
Появилась проблема редактирования профилей

### ISSUE THREAD

**Issue by Evgen-24** [weerci/LiteGeneLib#63]
Добавил профиль в «эксперт/контроль» из файла, два раза на него кликнул - редактировать не дает и при нажатии на кнопку "редактировать, тоже и попытке отредактировать следы:
![image](https://user-images.githubusercontent.com/45830240/50018330-84884080-0001-11e9-978d-5f930cba2c68.png)

**Comment by weerci** [comment]
Это старая база данных, возьми свежую версию
