### ISSUE TITLE
Не работает пароль доступа

### ISSUE THREAD

**Issue by weerci** [weerci/LiteGeneLib#87]
После создания пароля для администратора и модератора программа загружается, но активировать функционал администратора не получается. Работает только после перезагрузки программы

**Comment by Evgen-24** [comment]
Сегодня  немного полазил на работе, зашел под админом, сменил пароль админа, затем в разделе для пароля модератора задал пароль, но кнопка "сохранить" так и осталась не активна. Программу перезапускал - не помогло. Дома воспроизвести ошибку не смог. Жаль что модератор не может сам себе пароль сменить.

**Comment by weerci** [comment]
Пароль должен быть более 5 символов и совпадать

**Comment by weerci** [comment]
Функционал переделал теперь все по другому,так что это issue устарел. Надо смотреть #102
