### ISSUE TITLE
Версия базы данных

### ISSUE THREAD

**Issue by weerci** [weerci/LiteGeneLib#92]
Версия программы должна работать с соответствующей версией базы данных, если необходимо перенести данные из предыдущей версии - нужно воспользоваться импортом БД?

**Comment by Evgen-24** [comment]
Не понял идеи. Имеется ввиду жесткая привязка каждой версии программы к конкретной версии БД?

**Comment by weerci** [comment]
Ага

**Comment by Evgen-24** [comment]
Думал на этим. Как я понял, это еще один из вариантов защиты? Какие преимущества в защите ПО это даст?
А вот с другой стороны, не создаст ли это большие проблемы в случае дистанционной тех. поддержки?

**Comment by Evgen-24** [comment]
Вроде обсуждали несколько раз, сошлись что не нужно. (?)
