### ISSUE TITLE
Форма родства выбор ребенка

### ISSUE THREAD

**Issue by weerci** [weerci/LiteGeneLib#98]
При выборе профиля ребенка, если профиль содержит более 2 аллелей в локусе, появляется окно
![001](https://user-images.githubusercontent.com/5501362/62510240-75782c00-b838-11e9-948c-01218e3de445.PNG)

**Comment by weerci** [comment]
Сейчас вообще все отображает и считает как-то произвольно. Надо наверно запретить выбирать?

**Comment by Evgen-24** [comment]
Не понял вопрос. Что выбирать?
В стандартных случаях, да, в профилях должно быть не более 2 аллелей. Но встречаются (относительно редко) три аллеля в локусе (трисомия), Характерна при синдроме Дауна.

**Comment by weerci** [comment]
Хорошо, тогда закрываем
